# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xujiazhe's tech&life spot
email: woxujiazhe@gmail.com
description: > # this means to ignore newlines until "baseurl:" # 写一个网站的介绍，这个在head meta 里面出现(为了google的搜索) 而且在feed.xml 网站介绍里面
  My nickname could be surfree, I record my life and tech progress here.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xujiazhe.info" # the base hostname & protocol for your site
social_links: true
quora_username: Jiazhe-Xu
twitter_username: xujiazhe
github_username: xujiazhe

# Build settings
markdown: rdiscount
highlighter: pygments
# encoding: utf-8
