# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xujiazhe's tech&life spot
email: woxujiazhe@gmail.com
description: > # this means to ignore newlines until "baseurl:" # 写一个网站的介绍，这个在head meta 里面出现(为了google的搜索) 而且在feed.xml 网站介绍里面
  My nickname could be surfree, I record my life and tech progress here.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xujiazhe.github.io" # the base hostname & protocol for your site

social_links: [
  [Github, 'https://github.com/xujiazhe'],
  [Quora, 'https://www.quora.com/profile/Jiazhe-Xu'],
  [Twitter, 'https://twitter.com/xujiazhe'],
  [Linkedin, 'https://cn.linkedin.com/in/jiazhe-xu-03545548'],
  [豆瓣, 'https://www.douban.com/people/66868569/'],
  [知乎, 'https://www.zhihu.com/people/surfree'],
  [微博, 'https://weibo.com/u/2979811624'],
  [Google+, 'https://plus.google.com/111676680084673834081'],
  #[Topcoder, 'https://topcoder.com'],
  #[CodeForces, 'https://www.codeforces.com']
]
# Build settings
markdown: kramdown
highlighter: rouge
# encoding: utf-8
excerpt_separator: ""

# paginate: 5
